# ==========================================
# CONFIGURACION DEL SERVIDOR
# ==========================================
server.port=8080
# Opcional: define un prefijo global para todos tus endpoints (ej: http://localhost:8080/avendano/api/v1/trabajadores)
#server.servlet.context-path=/avendano

# Forzar la zona horaria en la serializacion de fechas (JSON)
spring.jackson.time-zone=America/Lima

# ==========================================
# CONFIGURACION DE BASE DE DATOS (MySQL)
# ==========================================
# Reemplaza 'tu_password' con la contrasena real de tu base de datos local
spring.datasource.url=jdbc:mysql://localhost:3306/control_asistencia_avendano?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# CONFIGURACION DE JPA / HIBERNATE
# ==========================================
# 'update' creara las tablas y columnas si no existen.
# Nota Senior: En produccion, esto DEBE cambiarse a 'validate' o 'none' y usar Flyway.
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola (util para debuggear el problema N+1)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Especificar el dialecto exacto mejora el rendimiento y evita advertencias en el log

# ==========================================
# CONFIGURACION DE SEGURIDAD (JWT)
# ==========================================
# Variables personalizadas para leerlas desde la clase de configuracion de seguridad
# La clave debe tener al menos 256 bits (32 caracteres) para el algoritmo HS256
security.jwt.secret=AvendanoTradingCompanySecretKey2026ParaControlDeAsistencia!
# Tiempo de expiracion en milisegundos (Ej: 86400000 ms = 24 horas)
security.jwt.expiration=86400000

# ==========================================
# CONFIGURACION DE CORS
# ==========================================
# Orígenes permitidos (separados por coma). En producción, reemplazar con el dominio real.
cors.allowed-origins=http://localhost:4200